name: Release new docker image associated to package

on:
  workflow_dispatch:
    inputs:
      library:
        description: "Library to build"
      args:
        description: "Additional space separated arguments to be passed to the build script. If empty, no arguments are passed"
  workflow_call:
    inputs:
      library:
        description: "Library to build"
        type: string
      args:
        description: "Additional space separated arguments to be passed to the build script. If empty, no arguments are passed"
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build docker image
        run: |
          LIBRARY=${{ (inputs || github.event.inputs).library }}
          ARGS="${{ (inputs || github.event.inputs).args }}"
          docker build --pull -t numericalpdes/base_images:${LIBRARY} -f ${LIBRARY}/Dockerfile --build-arg ARGS=${ARGS} .
      - name: Test docker image
        run: |
          LIBRARY=${{ (inputs || github.event.inputs).library }}
          docker run -i --rm numericalpdes/base_images:${LIBRARY} bash -c "cd /usr/local/share/fem-on-colab && wget https://github.com/multiphenics/nbvalx/raw/main/tests/notebooks/conftest.py -O ${LIBRARY}/conftest.py && pytest --nbval-cell-timeout=300 ${LIBRARY}/"
        shell: bash
      - name: Log into the docker registry
        if: github.repository == 'numerical-pdes/docker'
        run: docker login -u ${{ secrets.CI_REGISTRY_USER }} -p ${{ secrets.CI_REGISTRY_PASSWORD }}
      - name: Push to the docker registry
        if: github.repository == 'numerical-pdes/docker'
        run: |
          LIBRARY=${{ (inputs || github.event.inputs).library }}
          docker push numericalpdes/base_images:${LIBRARY}
