name: Release new docker image associated to package

on:
  workflow_dispatch:
    inputs:
      library:
        description: "Library to build"
      args:
        description: "Additional space separated arguments to be passed to the build script. If empty, no arguments are passed"
  workflow_call:
    inputs:
      library:
        description: "Library to build"
        type: string
      args:
        description: "Additional space separated arguments to be passed to the build script. If empty, no arguments are passed"
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      INSTALL_SCRIPTS: '/tmp/fem-on-colab-src'
    steps:
      - uses: actions/checkout@v3
      - name: Clone FEM on Colab repository
        uses: actions/checkout@v3
        with:
          repository: fem-on-colab/fem-on-colab
          path: ${INSTALL_SCRIPTS}
      - name: Build docker image
        run: |
          LIBRARY=${{ (inputs || github.event.inputs).library }}
          ARGS="${{ (inputs || github.event.inputs).args }}"
          docker build --pull -e INSTALL_SCRIPTS=${INSTALL_SCRIPTS} -V ${INSTALL_SCRIPTS}:${INSTALL_SCRIPTS} -t numericalpdes/base_images:${LIBRARY} -f ${LIBRARY}/Dockerfile --build-arg args=${ARGS} .
        shell: bash
      - name: Test docker image
        run: |
          LIBRARY=${{ (inputs || github.event.inputs).library }}
          if [[ -f ${INSTALL_SCRIPTS}/${LIBRARY}/build.sh ]]; then
            docker run -i -e INSTALL_SCRIPTS=${INSTALL_SCRIPTS} -V ${INSTALL_SCRIPTS}:${INSTALL_SCRIPTS} --rm numericalpdes/base_images:${LIBRARY} bash -c "pip3 install --no-dependencies git+https://github.com/multiphenics/nbvalx.git && cd ${INSTALL_SCRIPTS} && wget https://github.com/multiphenics/nbvalx/raw/main/tests/notebooks/conftest.py -O ${LIBRARY}/conftest.py && pytest --nbval-cell-timeout=300 ${LIBRARY}/"
          fi
        shell: bash
      - name: Log into the docker registry
        if: github.repository == 'numerical-pdes/docker'
        run: docker login -u ${{ secrets.CI_REGISTRY_USER }} -p ${{ secrets.CI_REGISTRY_PASSWORD }}
      - name: Push to the docker registry
        if: github.repository == 'numerical-pdes/docker'
        run: |
          LIBRARY=${{ (inputs || github.event.inputs).library }}
          docker push numericalpdes/base_images:${LIBRARY}
